DROP TABLE dbo.OrdenReconexion
DROP TABLE dbo.OrdenCorta
DROP TABLE dbo.DetalleConceptoCobroAgua
DROP TABLE dbo.MovimientoConsumo
DROP TABLE dbo.TipoMovimientoConsumo
DROP TABLE dbo.AguaDePropiedad
DROP TABLE dbo.DetalleConceptoCobro
DROP TABLE dbo.ConceptoCobroDePropiedad
DROP TABLE dbo.ConceptoCobro
DROP TABLE dbo.Factura
DROP TABLE dbo.EstadoFactura
DROP TABLE dbo.UsuarioDePropiedad
DROP TABLE dbo.PropietarioDePropiedad
DROP TABLE dbo.Usuario
DROP TABLE dbo.TipoUsuario
DROP TABLE dbo.Propiedad
DROP TABLE dbo.TipoUsoTerreno
DROP TABLE dbo.TipoZona
DROP TABLE dbo.Persona
DROP TABLE dbo.TipoDocumentoId